In [1]:
#importing libraries dataset
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('weight-height.csv')

In [5]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [4]:
df.replace(to_replace=["Male", "Female"], value=[1,0], inplace=True) #male=1 ' female=0'

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   int64  
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 200.6 KB


In [7]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [8]:
df.Gender.value_counts()

1    5000
0    3555
Name: Gender, dtype: int64

# Step 01 - Regression

In [9]:
#Seperate X,y
x = df.drop('Weight', axis=1)
y = df[['Weight']]

In [72]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [79]:
x.mean()

Gender     0.584454
Height    66.809925
dtype: float64

In [80]:
x.shape

(8555, 2)

In [74]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [76]:
y.mean()

Weight    165.632735
dtype: float64

In [78]:
y.shape

(8555, 1)

In [48]:
df_      = x.copy()

In [49]:
df_

Gender     Height
0          1  73.847017
1          1  68.781904
2          1  74.110105
3          1  71.730978
4          1  69.881796
...      ...        ...
8550       0  60.483946
8551       0  63.423372
8552       0  65.584057
8553       0  67.429971
8554       0  60.921791

[8555 rows x 2 columns]

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
# Split arrays or matrices into random train and test subset
train, test = train_test_split(df, test_size=.30) #testing data=30% ... between 0.0 & 1.0 and represent proportion of dataset

In [23]:
train.shape # size of dataframe/series which is equivalent to total number of elements.

(5988, 3)

In [24]:
test.shape # size of dataframe/series which is equivalent to total number of elements. 

(2567, 3)

In [25]:
train.head() # the first n (n=5 is default) rows for the object based on position

Gender     Height      Weight
1735       1  68.560854  186.401101
2723       1  64.032319  147.371284
8540       0  60.542595  134.713428
7398       0  62.343782  129.966183
8120       0  65.077331  152.074626

In [26]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=.30, random_state=0) #testing data=30%

In [29]:
xtrain.head() # the first n (n=5 is default) rows for the object based on position

Gender     Height
3197       1  69.689848
4394       1  66.299441
7711       0  63.261527
7019       0  62.035319
898        1  67.272171

In [28]:
ytrain.head() # the first n (n=5 is default) rows for the object based on position

Weight
3197  186.377448
4394  159.235988
7711  126.426793
7019  119.418135
898   187.363366

# Linear Regression

In [31]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [32]:
lr.fit(xtrain, ytrain) # training the model

LinearRegression()

In [33]:
m = lr.coef_ # Attributes- estimated coefficients for the linear regression problem
m

array([[19.67647385,  5.95976283]])

In [34]:
c = lr.intercept_ # Attributes - independent term in the linear model
c

array([-244.11178083])

In [82]:
yp = (19.67647385*1+5.95976283*69) - 244.11178083 # y = mx + c
yp

186.78832828999998

In [84]:
lr.predict([[1,69]])

C:\Users\msalm\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[186.78832817]])

In [85]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [87]:
df['predicted_Weight'] = lr.predict(x)
df.head() # the first n (n=5 is default) rows for the object based on position

Gender     Height      Weight  predicted_weight  predicted_Weight
0       1  73.847017  241.893563        215.675400        215.675400
1       1  68.781904  162.310473        185.488528        185.488528
2       1  74.110105  212.740856        217.243344        217.243344
3       1  71.730978  220.042470        203.064312        203.064312
4       1  69.881796  206.349801        192.043622        192.043622

In [91]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [92]:
# Mean squared/absolute error regression loss ... output is non-negative floating point. The best/perfect value is 0.0.
mse = mean_squared_error(ytest, lr.predict(xtest))
mae = mean_absolute_error(ytest, lr.predict(xtest))

In [93]:
mse

102.30154155088874

In [94]:
mae

8.029100527825232

In [95]:
# coefficient of determination of the prediction.
lr.score(xtest, ytest)

0.9025307579174771

In [97]:
lr.predict([[1,70]])

C:\Users\msalm\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[192.748091]])

# KNN Regreassion

In [98]:
from sklearn.neighbors import KNeighborsRegressor

In [102]:
kneigh = KNeighborsRegressor(n_neighbors=50)

In [103]:
kneigh.fit(xtrain, ytrain)

KNeighborsRegressor(n_neighbors=50)

In [104]:
kneigh.predict(xtest)

array([[157.62475021],
       [185.77627347],
       [150.47661482],
       ...,
       [161.36073345],
       [168.51384917],
       [139.52341939]])

In [105]:
mse = mean_squared_error(ytest, kneigh.predict(xtest))
mae = mean_absolute_error(ytest, kneigh.predict(xtest))

In [106]:
mse

106.35448226505267

In [108]:
mae

8.157125960930035

In [109]:
lr.score(xtest, ytest)

0.9025307579174771

In [110]:
lr.predict([[1,70]])

C:\Users\msalm\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[192.748091]])

# Step 02 - Classification

In [111]:
x = df.drop('Gender', axis=1)
y = df[['Gender']]

In [112]:
x.head()

Height      Weight  predicted_weight  predicted_Weight
0  73.847017  241.893563        215.675400        215.675400
1  68.781904  162.310473        185.488528        185.488528
2  74.110105  212.740856        217.243344        217.243344
3  71.730978  220.042470        203.064312        203.064312
4  69.881796  206.349801        192.043622        192.043622

In [113]:
y.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [114]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=.30, random_state=0) #testing data=30%

In [116]:
xtrain.head()

Height      Weight  predicted_weight  predicted_Weight
3197  69.689848  186.377448        190.899661        190.899661
4394  66.299441  159.235988        170.693636        170.693636
7711  63.261527  126.426793        132.911914        132.911914
7019  62.035319  119.418135        125.604008        125.604008
898   67.272171  187.363366        176.490875        176.490875

In [117]:
xtest.head()

Height      Weight  predicted_weight  predicted_Weight
541   63.867921  174.473363        156.202354        156.202354
3209  68.688931  178.507500        184.934429        184.934429
7598  65.865244  155.248900        148.429453        148.429453
5170  66.259558  138.839940        150.779470        150.779470
2423  67.290776  154.718344        176.601756        176.601756

In [ ]:
xtrain.head()

In [118]:
ytrain.head()

Gender
3197       1
4394       1
7711       0
7019       0
898        1

In [119]:
ytest.head()

Gender
541        1
3209       1
7598       0
5170       0
2423       1

In [120]:
from sklearn.neighbors import KNeighborsClassifier
kneigh2 = KNeighborsClassifier(n_neighbors = 50)

In [121]:
kneigh2.fit(xtrain, ytrain)

C:\Users\msalm\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=50)

In [122]:
yp2 = kneigh2.predict(xtest)

C:\Users\msalm\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
